version: 2
updates:
  # Python dependencies (Poetry)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    reviewers:
      - "nodite/dify-oapi2-maintainers"
    assignees:
      - "nodite/dify-oapi2-maintainers"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Group minor and patch updates together
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    # Ignore specific dependencies if needed
    ignore:
      # Example: ignore major version updates for stable dependencies
      # - dependency-name: "pydantic"
      #   update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    reviewers:
      - "nodite/dify-oapi2-maintainers"
    assignees:
      - "nodite/dify-oapi2-maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
